CREATE TABLE umd.dim_ilula_billing(
ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
CREATED_BY VARCHAR2(30 BYTE) DEFAULT ON NULL NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER) NOT NULL ENABLE, 
LAST_UPDATED_BY VARCHAR2(30 BYTE) DEFAULT ON NULL NVL(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER) NOT NULL ENABLE, 
CREATED_TIME DATE DEFAULT ON NULL SYSDATE NOT NULL ENABLE, 
LAST_UPDATED_TIME DATE DEFAULT ON NULL SYSDATE NOT NULL ENABLE);

begin
UMD.build_history_objects('UMD','DIM_ILULA_BILLING','ID');
end;
/

CREATE UNIQUE INDEX UMD.ILULA_BILLING_IDX ON UMD.dim_ilula_billing(offer_code,invoice_txt,default_invoice_txt,charge_txt);

alter table EBU_BRM_ACCOUNT_MAPPING_H move NOCOMPRESS

grant SELECT on umd.DIM_ILULA_BILLING to integration with grant option;

CREATE FORCE EDITIONABLE VIEW integration.DIM_ILULA_BILLING AS
SELECT * FROM umd.DIM_ILULA_BILLING;

grant select on integration.DIM_ILULA_BILLING to SU_IS_EVA;

:LAST_UPDATED_BY := :APP_USER;
:LAST_UPDATED_TIME := to_char(sysdate,'DD-MON-YYYY HH24:MI:SS');

--Dim Priceplan check
select payment_option, subscriber_category, count(1) cnt
from "INTEGRATION"."DIM_PRICEPLAN"
group by  payment_option, subscriber_category
order by  payment_option, subscriber_category


select * FROM VVHP_CUSTOMER_LIST
WHERE EXISTS (
    SELECT 1
    FROM CUSTOMER_CONSENT_LIST_UPLOAD
    WHERE CUSTOMER_CONSENT_LIST_UPLOAD.MSISDN = VVHP_CUSTOMER_LIST.MSISDN
);

--bulk delete
DELETE FROM VVHP_CUSTOMER_LIST
WHERE EXISTS (
    SELECT 1
    FROM CUSTOMER_CONSENT_LIST_UPLOAD
    WHERE CUSTOMER_CONSENT_LIST_UPLOAD.MSISDN = VVHP_CUSTOMER_LIST.MSISDN
);

commit;

--Delete duplicates

delete from umd.EBU_DEAL_MASTER_UPLOAD
where id in (
select id from (
	select a.*,
	row_number() over (partition by DEAL_ID order by DEAL_ID, START_DATE desc) rnk
	from EBU_DEAL_MASTER_UPLOAD a
	where DEAL_ID in (select DEAL_ID --, count(*) cnt
						from EBU_DEAL_MASTER_UPLOAD
						group by DEAL_ID
						having count(*) >1)
	order by DEAL_ID, START_DATE desc
) where rnk >1);

CREATE INDEX idx_msisdn_temp ON CUSTOMER_CONSENT_LIST_UPLOAD(MSISDN);

EVA user: su_is_azurede_prd 


RETURN REGEXP_LIKE(:PERIOD, '^[0-9]{4}(0[1-9]|1[0-2])$');

Please enter a valid YYYYMM format (e.g. 202501).

'MOMO_Summaries-DIM_TRANSACTING_CHANNEL','MOMO_SUMMARIES-MOMO_AGENT_BASE_DD' 



